[general]
working_directory = "~/"

# [terminal.shell]
# program = "/opt/homebrew/bin/zellij"
# args = ["attach", "-c", "root"]

[[keyboard.bindings]]
action = "ToggleSimpleFullscreen"
key = "Return"
mods = "Command"

[bell]
animation = "EaseOutExpo"
duration = 0

## sonokai

[colors.primary]
background = "0x2c2e34"
foreground = "0xe2e2e3"

[colors.normal]
black = "0x181819"
red = "0xfc5d7c"
green = "0x9ed072"
yellow = "0xe7c664"
blue = "0x76cce0"
magenta = "0xb39df3"
cyan = "0xf39660"
white = "0xe2e2e3"

[colors.bright]
black = "0x7f8490"
red = "0xfc5d7c"
green = "0x9ed072"
yellow = "0xe7c664"
blue = "0x76cce0"
magenta = "0xb39df3"
cyan = "0xf39660"
white = "0xe2e2e3"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "SauceCodePro Nerd Font"

[font.bold_italic]
family = "SauceCodePro Nerd Font"

[font.italic]
family = "SauceCodePro Nerd Font"

[font.normal]
family = "SauceCodePro Nerd Font"

[window]
decorations = "full"
# startup_mode = "SimpleFullscreen"
option_as_alt = "Both"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 4
y = 4

[keyboard]
