#!/bin/sh

# install NeoBundle
if [ ! -d ~/.vim/bundle ]; then
  mkdir -p ~/.vim/bundle
  git clone https://github.com/Shougo/neobundle.vim ~/.vim/bundle/neobundle.vim
fi

# Have Neobundle install all plugins
vim +NeoBundleInstall +qall -
# reset -Q
