#!/bin/sh

# This file is currently a placeholder for future endevours.

# Install prezto
if [ ! -d ~/.zprezto ]; then
  git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"
fi
